"""Create all table

Revision ID: 4c8321687d8a
Revises: 
Create Date: 2024-11-18 13:00:13.142768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8321687d8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('preferences', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('external_url', sa.VARCHAR(), nullable=True),
    sa.Column('date_start', sa.DATE(), nullable=True),
    sa.Column('date_end', sa.DATE(), nullable=True),
    sa.Column('location', sa.Enum('city1', 'city2', 'city3', 'city4', 'city5', name='location'), nullable=True),
    sa.Column('is_cyclically', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('main_user', sa.Integer(), nullable=True),
    sa.Column('group_members', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['main_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_event')
    op.drop_table('user_group')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('group_event')
    # ### end Alembic commands ###
