"""Update table group_event

Revision ID: 5ed7df6b6db4
Revises: a5492e3b0eed
Create Date: 2024-11-15 18:56:06.468501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed7df6b6db4'
down_revision: Union[str, None] = 'a5492e3b0eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
