version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["sh", "-c", "alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ADDRESS: db:5432
    env_file:
      - .env

volumes:
  postgres_data:
